# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skazka_dar',
            fields=[
                ('id_skazka', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/img')),
            ],
            options={
                'verbose_name': 'Сказка',
                'verbose_name_plural': 'Сказки',
            },
        ),
    ]
